Repository JNU-econovation/EATceed-BE, pull requests merged in 2023-12, with the labels that each got.

#8 [AI/setting] self-instruction 필요 파일 세팅
  AI/dataset/instruction/machine_generated_instructions.jsonl
  AI/dataset/instruction/seed_tasks.jsonl
  AI/self_instruct/prompt.txt
Labels: AI, setting

#10 [AI/feat] gpt api를 이용한 self-instruct 코드 구현
  AI/self_instruct/generate_instruction.py
  AI/self_instruct/gpt_api.py
Labels: AI, feature

#14 [BE/feat] 필요 칼로리들을 계산하여 반환하는 유스케이스 구현
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/DecimalUtil.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/CreateMemberRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/CurrentMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMealNutritionResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/MaintainMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/TargetMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/domain/FoodModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/MealModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/port/in/GetCurrentMealQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/port/out/LoadMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/CreateMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/CreateMemberCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/CreateMemberUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetMaintainMealUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetTargetMealUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/LoadMemberPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/Activity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/MemberModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/PhysiqueModel.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/GetMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/application/CreateMemberServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/domain/PhysiqueModelTest.java
Labels: BE, feature

#20 [AOS/Setting] : 프로젝트 생성 및 버전 업데이트
  AOS/.gitignore
  AOS/app/.gitignore
  AOS/app/build.gradle.kts
  AOS/app/proguard-rules.pro
  AOS/app/src/androidTest/java/com/gaebaljip/exceed/ExampleInstrumentedTest.kt
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/com/gaebaljip/exceed/MainActivity.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/ui/theme/Color.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/ui/theme/Theme.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/ui/theme/Type.kt
  AOS/app/src/main/res/drawable/ic_launcher_background.xml
  AOS/app/src/main/res/drawable/ic_launcher_foreground.xml
  AOS/app/src/main/res/mipmap-anydpi/ic_launcher.xml
  AOS/app/src/main/res/mipmap-anydpi/ic_launcher_round.xml
  AOS/app/src/main/res/mipmap-hdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-hdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-mdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-mdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xxhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/mipmap-xxxhdpi/ic_launcher.webp
  AOS/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.webp
  AOS/app/src/main/res/values/colors.xml
  AOS/app/src/main/res/values/strings.xml
  AOS/app/src/main/res/values/themes.xml
  AOS/app/src/main/res/xml/backup_rules.xml
  AOS/app/src/main/res/xml/data_extraction_rules.xml
  AOS/app/src/test/java/com/gaebaljip/exceed/ExampleUnitTest.kt
  AOS/build.gradle.kts
  AOS/gradle.properties
  AOS/gradle/wrapper/gradle-wrapper.jar
  AOS/gradle/wrapper/gradle-wrapper.properties
  AOS/gradlew
  AOS/gradlew.bat
  AOS/settings.gradle.kts
Labels: AOS, setting

#22 [AOS/feat] : request DTO 패키지 및 파일 생성
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/FoodInfoRequestDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/FoodRegistrationRequestDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/OnboardingRequestDTO.kt
Labels: AOS, feature

#23 [AI/feat] 음식 등록을 위한 음식 데이터(Raw data) 가공
  AI/dataset/food/csv_to_json.ipynb
  AI/dataset/food/food_data.csv
  AI/dataset/food/food_data.json
Labels: AI, feature

#24 [BE/feat] 특정 일자 식사 분석해주는 유스케이스 구현
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/adapter/in/GetAchieveController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/application/GetAchieveService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMealFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMealFoodResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMealResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/out/LoadFoodsSpecificDate.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetSpecificMealQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/GetMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberControllerTest.java
Labels: BE, feature

#26 [AI/feat] QLoRA(Fine-Tuning) KoAlpaca-Polyglot-5.8B 모델 적용
  AI/fine_tuning/Food_Recys_KoAlpaca_QLoRA_FineTuning.ipynb
Labels: AI, feature

#27 [BE/fix] 정의되지 않은 enum 값이 올 때에도 통일성 있는 예외 메시지 응답하기
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/Activity.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberControllerTest.java
Labels: bug, BE, refactor

#32 [BE/feat] 식사 등록하는 기능 구현
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/application/GetAchieveService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MessageCode.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/EatMealRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/out/LoadFoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/exception/FoodExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/exception/FoodNotFoundException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealFoodEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealFoodPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealFoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/EatMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetPreSignedUrlService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/EatMealCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/EatMealUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetPreSignedUrlUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/RecordMealFoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/RecordMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/MealModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/exception/InvalidMultipleException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/exception/MealExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/CreateMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/MemberConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/CreateMemberCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/LoadMemberPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/exception/InvalidAgeException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/exception/InvalidGenderException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/exception/InvalidHeightException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/exception/InvalidWeightException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/exception/MemberExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/exception/MemberNotFoundException.java
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/db/testSetUp.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/DatabaseClearExtension.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/IntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/CreateMemberIntegrationTest.java
Labels: BE, feature

#34 [BE/feat] 식사 등록하는 기능 구현
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/adapter/in/GetAchieveController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/application/GetAchieveService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/application/port/in/GetAchieveUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/CustomDoubleSerializer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/DateConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/TimeConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/CurrentMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/MaintainMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/TargetMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/CreateMemberRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/EatMealRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/CurrentMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetAchieve.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetAchieveListResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetMealFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetMealFoodResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetMealResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/MaintainMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/TargetMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealFoodEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetCurrentMealQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetSpecificMealQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/LoadMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/MealModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/MealsModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/MemberConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetMaintainMealUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetTargetMealUsecase.java
  BE/exceed/src/main/resources/db/testSetUp.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/GetMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/CreateMemberIntegrationTest.java
Labels: BE, feature

#36 [BE/feat] 해당 월의 달성 여부 보여주는 기능 구현
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/adapter/in/GetAchieveController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/application/GetAchieveService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/application/port/out/LoadMonthMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/application/port/out/LoadMonthTargetPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/domain/Achieve.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/domain/AchieveModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/domain/DailyRecord.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/domain/DailyTarget.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/exception/AchieveExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/exception/MealNotFoundException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MessageCode.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetAchieve.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetAchieveListResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/LoadDailyMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/MealsModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/resources/db/testSetUp.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/achieve/GetAchieveIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/achieve/adapter/in/GetAchieveControllerTest.java
Labels: BE, feature, refactor

#40 [BE/feat] 음식 제공해주는 기능 구현
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/QueryDslConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetPageableFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/PageableFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/QueryDslFoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/out/LoadFoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetFoodQuery.java
  BE/exceed/src/main/resources/db/testSetUp.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/GetMealControllerTest.java
Labels: BE, feature
