Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-01, with the labels that each got.

#43 [BE/feat] presignedUrl 관련 기능 구현 및 배포
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MessageCode.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/S3Config.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/EatMealRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/EatMealResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/UploadImage.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealFoodEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/S3Adapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/EatMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetPreSignedUrlService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/UploadImageService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetPreSignedUrlUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/UploadImageUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/GetPresignedUrlPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/RecordMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/MealModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/exception/ExtentionNotAllowedException.java
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/main/resources/db/data.sql
  BE/exceed/src/main/resources/db/mockData.sql
  BE/exceed/src/main/resources/db/schema.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/config/MockS3Config.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
Labels: BE, feature, refactor

#44 [AOS/setting] API Response DTO들 생성
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/CalendarDetailResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/CalendarInfoResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/FoodInfoResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/FoodListPagingResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/HomeInfoResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/OnboardingResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/RegisterFoodInfoResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/common/CommonMealInfo.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/common/CommonResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/common/ErrorStatusDTO.kt
Labels: AOS, setting

#46 [AOS/setting] Analytics 사용 설정
  AOS/app/build.gradle.kts
  AOS/build.gradle.kts
Labels: AOS, setting

#48 [BE/feat] FE 요청에따른 응답 DTO 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/CurrentMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/DailyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/MaintainMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/TargetMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java
Labels: BE, refactor

#51 [AOS/feat] 진행도 게이지
  AOS/app/src/main/java/com/gaebaljip/exceed/ui/common/AchieveGaugeComponent.kt
  AOS/app/src/main/res/values/colors.xml
Labels: AOS, feature

#54 [AI/feat] AI Merge to main branch
  AI/dataset/food/csv_to_json.ipynb
  AI/dataset/food/food_data.csv
  AI/dataset/food/food_data.json
  AI/dataset/instruction/machine_generated_instructions.jsonl
  AI/dataset/instruction/seed_tasks.jsonl
  AI/fine_tuning/Food_Recys_KoAlpaca_QLoRA_FineTuning.ipynb
  AI/self_instruct/generate_instruction.py
  AI/self_instruct/gpt_api.py
  AI/self_instruct/prompt.txt
Labels: AI

#55 [AOS/feat] 바텀 네비게이션 바, 화면 전환
  AOS/app/build.gradle.kts
  AOS/app/src/main/java/com/gaebaljip/exceed/BottomNavItem.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/MainActivity.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/AddScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/AlarmScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/CalendarScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/FoodScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/HomeScreen.kt
  AOS/app/src/main/res/drawable/ic_add.xml
  AOS/app/src/main/res/drawable/ic_alarm.xml
  AOS/app/src/main/res/drawable/ic_calendar.xml
  AOS/app/src/main/res/drawable/ic_food.xml
  AOS/app/src/main/res/drawable/ic_home.xml
Labels: AOS, feature

#57 [PM/setting] Issue, PR 템플릿 수정
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: setting, PM

#61 [BE/feat] 게스트용 온보딩
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/CreateGuestRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/CreateGuestResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/CreateGuestService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/MemberConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/CreateGuestUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/CreateMemberUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/RecordMemberPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/GuestIdGenerator.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/GuestModel.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/MemberRole.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/RandomIndexes.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/RandomWord.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/AuthConstants.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtManager.java
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/main/resources/db/data.sql
  BE/exceed/src/main/resources/db/mockData.sql
  BE/exceed/src/main/resources/db/schema.sql
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/CreateGuestIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestTestRequest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/application/CreateGuestServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/security/JwtManagerTest.java
Labels: BE, feature, refactor

#64 [AOS/setting] Material color, fontstyle 등록
  AOS/app/src/main/java/com/gaebaljip/exceed/ui/theme/Type.kt
  AOS/app/src/main/res/font/gmarketsans_bold.otf
  AOS/app/src/main/res/font/gmarketsans_light.otf
  AOS/app/src/main/res/font/gmarketsans_medium.otf
  AOS/app/src/main/res/font/pretendard_bold.otf
  AOS/app/src/main/res/font/pretendard_extrabold.otf
  AOS/app/src/main/res/font/pretendard_light.otf
  AOS/app/src/main/res/font/pretendard_medium.otf
  AOS/app/src/main/res/font/pretendard_regular.otf
  AOS/app/src/main/res/font/pretendard_thin.otf
  AOS/app/src/main/res/values/colors.xml
Labels: AOS, setting

#68 [BE/feat] 게스트 인증/인가 기능 개발
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/adapter/in/GetAchieveController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/AuthenticationMemberId.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/AuthenticationMemberIdArgumentResolver.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/Enum.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/EnumValidator.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/WebConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/CreateGuest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/CreateGuestResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/CreateGuestService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/MemberConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/CreateGuestUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/CustomUsernamePasswordAuthenticationToken.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtAccessDeniedHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtAuthenticationFilter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtAuthenticationPoint.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtManager.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtResolver.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/MemberDetailService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/MemberDetails.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/PasswordEncoderConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/SecurityConfig.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/achieve/GetAchieveIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/achieve/adapter/in/GetAchieveControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/WithCustomMockUserSecurityContextFactory.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/WithMockGuestUser.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/GetMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/CreateGuestIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/security/JwtManagerTest.java
Labels: BE, feature

#72 [BE/feat] 인증/인가 커스텀 예외 처리
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/GlobalExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MessageCode.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtAccessDeniedHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtAuthenticationFilter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtManager.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/config/PasswordEncoderConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/config/SecurityConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/ExpiredJwtAuthenticationException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/InvalidJwtAuthenticationException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/JwtAccessDeniedHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/JwtAuthenticationPoint.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/UnsupportedAuthenticationException.java
  BE/exceed/src/main/resources/db/schema.sql
Labels: BE, feature, refactor

#74 [BE/hotfix] 요청 1번에 응답 2개가 합쳐서 오는 오류 해결
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtAuthenticationFilter.java
  BE/exceed/src/main/resources/db/schema.sql
Labels: bug, BE

#76 [AOS/feat] 캘린더 화면 레이아웃 및 컴포넌트 배치
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/CalendarScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/ui/theme/Type.kt
  AOS/app/src/main/res/values/colors.xml
Labels: AOS, feature

#77 [BE/docs] Spring REST Docs
  BE/exceed/.gitignore
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/config/SecurityConfig.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/achieve/GetAchieveIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/CommonApiTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/IntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestControllerTest.java
Labels: BE, document

#80 [AOS/feat] 알람 설정 화면 UI
  AOS/app/src/main/java/com/gaebaljip/exceed/MainActivity.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/MealTypeEnum.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/AlarmScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/alarm/AlarmInfo.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/alarm/AlarmScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/alarm/AlarmViewModel.kt
  AOS/app/src/main/res/drawable/add_icon.xml
  AOS/app/src/main/res/drawable/delete_icon.xml
  AOS/app/src/main/res/values/colors.xml
  AOS/app/src/main/res/values/strings.xml
Labels: AOS, feature

#86 [AOS/feat] 캘린더 ViewModel 생성
  AOS/app/src/main/java/com/gaebaljip/exceed/MainActivity.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/calendar/CalendarScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/calendar/CalendarViewModel.kt
Labels: AOS, feature

#93 [AOS/feat] 로그인, 온보딩 UI 추가
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/LoginScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/OnboardingScreen.kt
Labels: AOS, feature

#96 [AOS/feat] OnboardActivity 생성 및 Activity 전환 구현
  AOS/app/src/main/AndroidManifest.xml
  AOS/app/src/main/java/com/gaebaljip/exceed/OnboardActivity.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/LoginScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/OnboardingScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/alarm/AlarmScreen.kt
Labels: AOS, feature

#97 [BE/feat] Logback 적용
  BE/exceed/.gitignore
  BE/exceed/src/main/java/com/gaebaljip/exceed/ExceedApplication.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/GlobalExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/AuthenticationMemberIdArgumentResolver.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/log/LoggingFilter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/S3Adapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/config/SecurityConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/domain/CustomUsernamePasswordAuthenticationToken.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/domain/JwtManager.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/domain/JwtResolver.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/domain/MemberDetails.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/JwtAccessDeniedHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/JwtAuthenticationPoint.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/filter/JwtAuthenticationFilter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/service/MemberDetailService.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/WithCustomMockUserSecurityContextFactory.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/security/JwtManagerTest.java
Labels: BE, feature

#99 [AOS/feat] 온보딩 입력 데이터와 ViewModel, RequestDTO 연결
  AOS/app/build.gradle.kts
  AOS/app/src/main/java/com/gaebaljip/exceed/APIService.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/ActiveTypeEnum.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/OnboardingViewModel.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/OnboardingRequestDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/OnboardingScreen.kt
Labels: AOS, feature

#101 [BE/docs] Rest Docs 보충
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/achieve/GetAchieveIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/util/ApiDocumentUtil.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/CreateGuestIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestControllerTest.java
Labels: BE, document

#103 fix/#102 : WebMvcConfiguration -> WebMvcConfigurer로 교체
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/WebConfig.java
Labels: BE, fix

#111 [AI/feat] 챗봇 서버 DB 연결
  AI/server/core/config.py
  AI/server/db/crud.py
  AI/server/db/database.py
  AI/server/db/models.py
  AI/server/db/schemas.py
  AI/server/main.py
Labels: AI, feature

#113 [AI/feat] 챗봇 서버 JWT Token Decode
  AI/server/main.py
Labels: AI, feature

#115 feat: Curl을 이용한 Test 진행
  AI/server/main.py
  AI/server/test/curl.py
Labels: AI, feature

#117 [AI/feat] 환경 변수 설정
  AI/server/.gitignore
  AI/server/core/config.py
Labels: AI, feature

#119 [AI/fix] .env value 값 변경
  AI/server/main.py
Labels: AI, fix

#121 [AI/setting] AWS EC2 배포를 위한 사전작업
  AI/server/requirements.txt
Labels: AI, setting

#123 [AI/feat] 배포를 위한 환경변수 변경
  AI/server/core/config.py
  AI/server/main.py
Labels: AI, fix

#105 [AOS/feat] 음식 추천 챗봇 화면 구현
  AOS/app/src/main/java/com/gaebaljip/exceed/APIService.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/FoodViewModel.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/OnboardingViewModel.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/ChattingRequestDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/ChattingResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/RemoteDataSource.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/FoodScreen.kt
  AOS/app/src/main/res/drawable/send_icon.xml
Labels: AOS, feature

#126 [AI/feat] 로그 메시지 시간 출력
  AI/server/main.py
Labels: AI, feature

#128 Feat/#127
  .gitignore
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/QueryDslFoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/out/LoadFoodPort.java
  BE/exceed/src/main/resources/db/data.sql
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
Labels: BE, feature

#132 [AOS/feat] DEV 전 merge
  AOS/app/src/main/java/com/gaebaljip/exceed/APIService.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/FoodViewModel.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/ChattingRequestDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/CalendarInfoResponseDTO.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/RemoteDataSource.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/FoodScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/calendar/CalendarScreen.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/calendar/CalendarViewModel.kt
  AOS/app/src/main/res/drawable/back_icon.xml
  AOS/app/src/main/res/drawable/forward_icon.xml
Labels: AOS, feature

#134 [AI/fix] response 변수 이름 변경
  AI/server/main.py
Labels: AI, fix

#135 [AOS/feat] 챗봇 답변 수신
  AOS/app/src/main/java/com/gaebaljip/exceed/FoodViewModel.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/RemoteDataSource.kt
  AOS/app/src/main/java/com/gaebaljip/exceed/screens/FoodScreen.kt
Labels: AOS, feature
