Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-12, with the labels that each got.

#586 [BE/FIX] RedisAutoComplete 수정
  src/main/java/com/gaebaljip/exceed/common/data/RedisAutoComplete.java
  src/test/java/com/gaebaljip/exceed/integration/food/GetFoodIntegrationTest.java
Labels: BE, fix

#591 [BE/FEAT] 켈린더 상세 API에 식사별 총 칼로리 값 추가
  src/main/java/com/gaebaljip/exceed/adapter/out/aws/S3Adapter.java
  src/main/java/com/gaebaljip/exceed/application/port/out/meal/PresignedUrlPort.java
  src/main/java/com/gaebaljip/exceed/application/service/meal/GetSpecificMealService.java
  src/main/java/com/gaebaljip/exceed/application/service/meal/UploadImageService.java
  src/main/java/com/gaebaljip/exceed/common/dto/MealRecordDTO.java
Labels: BE, feature, refactor

#589 [BE/FIX] 식사 도메인의 영양소 계산 로직 수정
  src/main/java/com/gaebaljip/exceed/application/domain/meal/GStrategy.java
Labels: bug, BE

#593 [BE/FIX] 유지 및 목표 단/탄/지 구하는 수식 수정
  src/main/java/com/gaebaljip/exceed/application/domain/member/Member.java
Labels: BE, fix

#595 [BE/FEAT] 공지사항 기능
  resources/gaebaljip-develop-environment/mariadb-init/01_schema.sql
  resources/gaebaljip-local-environment/mariadb-init/01_schema.sql
  src/main/java/com/gaebaljip/exceed/adapter/in/announce/CreateAnnounceController.java
  src/main/java/com/gaebaljip/exceed/adapter/in/announce/GetAnnounceController.java
  src/main/java/com/gaebaljip/exceed/adapter/in/announce/request/CreateAnnounceRequest.java
  src/main/java/com/gaebaljip/exceed/adapter/in/announce/response/GetAnnounceResponse.java
  src/main/java/com/gaebaljip/exceed/adapter/out/jpa/announce/AnnouncePersistenceAdapter.java
  src/main/java/com/gaebaljip/exceed/adapter/out/jpa/announce/AnnounceRepository.java
  src/main/java/com/gaebaljip/exceed/application/domain/announce/AnnounceEntity.java
  src/main/java/com/gaebaljip/exceed/application/port/in/announce/CreateAnnounceUseCase.java
  src/main/java/com/gaebaljip/exceed/application/port/in/announce/GetAnnounceQuery.java
  src/main/java/com/gaebaljip/exceed/application/port/out/announce/AnnouncePort.java
  src/main/java/com/gaebaljip/exceed/application/service/announce/CreateAnnounceService.java
  src/main/java/com/gaebaljip/exceed/application/service/announce/GetAnnounceService.java
  src/main/java/com/gaebaljip/exceed/common/docs/SwaggerTag.java
  src/main/java/com/gaebaljip/exceed/common/dto/AnnounceDTO.java
  src/main/java/com/gaebaljip/exceed/common/exception/announce/AnnounceError.java
  src/main/java/com/gaebaljip/exceed/common/exception/announce/AnnounceNotFoundException.java
Labels: BE, feature

#596 [BE/FEAT] 약관 및 개인 정보 처리 방침 동의하기
  resources/gaebaljip-develop-environment/mariadb-init/01_schema.sql
  resources/gaebaljip-local-environment/mariadb-init/01_schema.sql
  resources/gaebaljip-local-environment/mariadb-init/02_data.sql
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/GetAgreementController.java
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/response/GetPrivacyPolicyResponse.java
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/response/GetTermsServiceAgreeResponse.java
  src/main/java/com/gaebaljip/exceed/adapter/in/member/request/SignUpMemberRequest.java
  src/main/java/com/gaebaljip/exceed/adapter/out/jpa/agreement/AgreementPersistenceAdapter.java
  src/main/java/com/gaebaljip/exceed/adapter/out/jpa/agreement/AgreementRepository.java
  src/main/java/com/gaebaljip/exceed/application/domain/agreement/AgreementEntity.java
  src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  src/main/java/com/gaebaljip/exceed/application/port/in/agreement/GetAgreementQuery.java
  src/main/java/com/gaebaljip/exceed/application/port/out/agreement/AgreementPort.java
  src/main/java/com/gaebaljip/exceed/application/service/agreement/GetAgreementService.java
  src/main/java/com/gaebaljip/exceed/application/service/member/CreateMemberService.java
  src/main/java/com/gaebaljip/exceed/common/docs/SwaggerTag.java
  src/main/java/com/gaebaljip/exceed/common/docs/member/SignUpMemberExceptionDocs.java
  src/main/java/com/gaebaljip/exceed/common/dto/GetAgreementDTO.java
  src/main/java/com/gaebaljip/exceed/common/exception/agreement/AgreementError.java
  src/main/java/com/gaebaljip/exceed/common/exception/agreement/InvalidAgreementException.java
  src/main/resources/db/testData.sql
  src/main/resources/db/testData_signup_after_2days_onboarding.sql
  src/test/java/com/gaebaljip/exceed/application/member/CreateMemberServiceTest.java
  src/test/java/com/gaebaljip/exceed/integration/member/OnBoardingMemberIntegrationTest.java
  src/test/java/com/gaebaljip/exceed/integration/member/SignUpMemberIntegrationTest.java
  src/test/java/com/gaebaljip/exceed/integration/member/VerifyEmailCheckedIntegrationTest.java
Labels: BE, feature

#598 [BE/FEAT] 약관 및 개인 정보 처리 방침 수정하기
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/GetAgreementController.java
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/UpdateAgreementController.java
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/request/AgreePrivacyPolicyRequest.java
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/request/AgreeTermsServiceRequest.java
  src/main/java/com/gaebaljip/exceed/adapter/out/jpa/agreement/AgreementPersistenceAdapter.java
  src/main/java/com/gaebaljip/exceed/adapter/out/jpa/agreement/AgreementRepository.java
  src/main/java/com/gaebaljip/exceed/application/domain/agreement/AgreementEntity.java
  src/main/java/com/gaebaljip/exceed/application/port/in/agreement/AgreePrivacyPolicyUsecase.java
  src/main/java/com/gaebaljip/exceed/application/port/in/agreement/AgreeTermsUsecase.java
  src/main/java/com/gaebaljip/exceed/application/port/out/agreement/AgreementPort.java
  src/main/java/com/gaebaljip/exceed/application/service/agreement/AgreePrivacyPolicyService.java
  src/main/java/com/gaebaljip/exceed/application/service/agreement/AgreeTermsService.java
  src/main/java/com/gaebaljip/exceed/common/docs/agreement/AgreePrivacyPolicyDocs.java
  src/main/java/com/gaebaljip/exceed/common/docs/agreement/AgreeTermsServiceDocs.java
  src/main/java/com/gaebaljip/exceed/common/exception/agreement/AgreementError.java
  src/main/java/com/gaebaljip/exceed/common/exception/agreement/AgreementNotFoundException.java
  src/main/java/com/gaebaljip/exceed/common/exception/agreement/InvalidPrivacyPolicyStatusException.java
  src/main/java/com/gaebaljip/exceed/common/exception/agreement/InvalidTermsServiceStatusException.java
Labels: BE, feature

#609 [BE/FIX] CI를 성공시킨다.
  src/test/java/com/gaebaljip/exceed/common/SchemaValidationTest.java
Labels: BE, fix

#611 [BE/FEAT] 운영 로그 masking 처리하기
  src/main/java/com/gaebaljip/exceed/common/log/MaskingPatternLayout.java
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/logback-spring.xml
  src/test/java/com/gaebaljip/exceed/common/SchemaValidationTest.java
Labels: BE, feature
