Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-08, with the labels that each got.

#452 [Be/Feat] 분석 API 쿼리 개선
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealFoodConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealFoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealRepository.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapterTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/DatabaseTest.java
Labels: BE, test, improvement

#455 [BE/FIX] 분석 조회 API 오류 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealFoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/HistoryPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/MonthlyAnalyzer.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/domain/nutritionist/MonthlyAnalyzerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/factory/MonthlyMealFixtureFactory.java
Labels: BE, fix

#458 [BE/TEST] SSE 테스트
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/scheduler/quartz/UpdateWeightEventListener.java
Labels: BE, test

#469 [BE/PERF] 홈화면 API와 켈린더 상세 조회 API에 사용되는 쿼리 개선
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/meal/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/CreateMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/ValidateEmailService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetAllCalorieAnalysisService.java
Labels: BE, improvement

#472 [BE/REFACTOR] Meal 과 MealEntity 통합
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/response/GetFoodResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/food/FoodConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/food/FoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/food/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/food/QueryDslFoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/ConsumedFoodConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealFoodConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/food/Food.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/food/FoodEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/ConsumedFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/DailyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/DailyMealFoods.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/Meal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/MealEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/MealFoodEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/Unit.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/AbstractAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyCalorieAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyCalorieAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyCarbohydrateAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyCarbohydrateAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyFatAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyFatAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyMealAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyProteinAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/DailyProteinAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/MonthlyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/VisitChecker.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/food/FoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/meal/DailyMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/food/CreateFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/food/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/meal/EatMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/meal/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/meal/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetAllCalorieAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/data/MariaDBAutoComplete.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/AllAnalysisDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/PageableFoodDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/handler/DeleteMemberEventListener.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapterTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/domain/meal/DailyMealFoodsTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/domain/meal/DailyMealTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/domain/nutritionist/CalorieDailyMealFoodsAnalyzerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/service/nutritionist/GetAllCalorieAnalysisServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/DatabaseTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/factory/DailyMealFoodsFixtureFactory.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/factory/MonthlyMealFixtureFactory.java
Labels: BE, refactor

#475 [BE/FEAT] 프로메테우스 Tomcat 설정 추가
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-prod.yml
Labels: BE, feature
