Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-09, with the labels that each got.

#481 [BE/FEAT] AOS 딥링크 적용으로 인한 메일 인증 방식 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/CheckMemberEmailController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/EmailConfirmedController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/redis/RedisAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/member/Code.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/EmailConfirmedUseCase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/GetCodeUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/member/CodePort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/CheckCodeService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/EmailConfirmedService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/GetCodeService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/Encryption.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MailTemplate.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/handler/SendEmailEventListener.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/security/config/SecurityConfig.java
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-prod.yml
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/main/resources/templates/signup.html
Labels: BE, feature

#484 [BE/FEAT] 이메일 인증을 하지 않아 회원가입을 2번 이상 시도한 회원들에게 이메일 재전송하는 기능
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/CheckMemberEmailController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/SignUpMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/redis/RedisAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/SendEmailCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/SendEmailUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/ValidateEmailCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/ValidateSignUpCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/ValidateSignUpUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/CheckCodeService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/CreateMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/GetCodeService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/SendSignupEmailService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/ValidateEmailService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/ValidateSignUpService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/ApiResponseGenerator.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/Encryption.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MailTemplate.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/member/CheckMemberEmailExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/member/SignUpMemberExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/IncompleteSignUpEvent.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/SignUpMemberEvent.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/handler/InCompleteSignUpMemberEventListener.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/handler/SignUpMemberEventListener.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/GlobalExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/member/ExpiredCodeException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/member/MemberError.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/member/RedirectException.java
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/member/CreateMemberServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/member/ValidateEmailServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/SignUpMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/VerifyEmailCheckedIntegrationTest.java
Labels: BE, feature

#503 [AI/feat] docker-compose를 이용한 EC2 배포 및 포트포워딩 적용
  AI/docker-compose.yml
  AI/food_classification/Dockerfile
  AI/food_classification/src/config.properties
Labels: AI, feature

#509 [AI/feat] Torchserve 요청 관련 에러
  AI/food_classification/src/config.properties
  AI/server/auth/decoded_token.py
  AI/server/errors/custom_exceptions.py
  AI/server/errors/error_hanlder.py
  AI/server/routers/diet_analysis.py
Labels: AI, fix
