Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-04, with the labels that each got.

#168 [BE/feat] 온보딩 기능 수정
  BE/exceed/resources/gaebaljip-local-develop-environment/mariadb-init/01_schma.sql
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/EnumValidator.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/OnBoardingMemberRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/OnBoardingController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/SignUpMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/GenderConvert.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/WeightEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/MemberConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/OnBoardingMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/OnBoardingMemberCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/OnBoardingMemberUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/Gender.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/Member.java
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/main/resources/db/data.sql
  BE/exceed/src/main/resources/db/schema.sql
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/WithCustomMockUserSecurityContextFactory.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/WithMockUser.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/SpecificMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/SpecificMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/OnBoardingMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/OnBoardingControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/application/OnBoardingMemberServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/nutritionist/GetAchieveIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/nutritionist/adapter/in/GetAchieveControllerTest.java
Labels: BE, feature, refactor

#170 [BE/feat] 로그인
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/adapter/AuthController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/application/port/AuthService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/application/port/in/AuthUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/exception/AuthExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/exception/MemberNotCheckedException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/exception/PasswordMismatchException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MessageCode.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/ValidationMessage.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/Password.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/PasswordValidator.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/LoginRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/SignUpMemberRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/LoginResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/CreateMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/MemberPort.java
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/auth/AuthControllerIntegrationTest.java
Labels: BE, feature

#171 [AI/feat] 음식 데이터 전처리 진행
  AI/data/food/.gitignore
  AI/data/food/food_data_preprocessing.ipynb
  AI/data/food/food_data_preprocessing.py
Labels: AI, feature

#173 [AI/fix] AI 서버 디렉토리 재구성 및 .gitignore 파일 문제 해결
  AI/data/food/food_data_preprocessing.ipynb
  AI/data/food/food_data_preprocessing.py
  AI/server/__pycache__/main.cpython-39.pyc
  AI/server/detect_model/food_classification/ckpt/pt.txt
  AI/server/detect_model/food_classification/src/403foodnames.txt
  AI/server/detect_model/food_classification/src/darknet.py
  AI/server/detect_model/food_classification/src/handler.py
  AI/server/detect_model/model.py
  AI/server/detect_model/model/config/config_properies.txt
  AI/server/detect_model/model/model_store/mar_file.txt
  AOS/Android.md
Labels: AI, fix

#178 [AI/setting] fork 재수행을 위한 세팅
  AI/server/apis/api.py
  AI/server/core/config.py
  AI/server/db/crud.py
  AI/server/db/database.py
  AI/server/main.py
  AI/server/prompts/prompt1.txt
  AI/server/prompts/prompt2.txt
  AI/server/routers/test.py
Labels: AI, setting

#180 [AI/feat] knhanes 데이터 전처리 수행
  AI/data/diet/.gitignore
  AI/data/diet/Hn19_22_preprocessed.csv
  AI/data/diet/knhanes_Data_Preprocessing.ipynb
Labels: AI, feature

#185 Fix/#183
  BE/exceed/Dockerfile
  BE/exceed/docker-compose.yml
  BE/exceed/resources/.DS_Store
  BE/exceed/resources/gaebaljip-local-develop-environment/.DS_Store
  BE/exceed/resources/gaebaljip-local-develop-environment/mariadb-init/00_init.sql
  BE/exceed/resources/gaebaljip-local-develop-environment/mariadb-init/01_schma.sql
  BE/exceed/resources/gaebaljip-local-develop-environment/mariadb-init/02_data.sql
  BE/exceed/resources/gaebaljip-local-develop-environment/setting.yml
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MailTemplate.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/RedisAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/SendSignupEmailService.java
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-test.yml
Labels: feature

#190 [AI/feat] 식습관 분석 프롬프트 작성
  AI/server/prompts/health_advice.txt
  AI/server/prompts/prompt1.txt
  AI/server/prompts/prompt2.txt
  AI/server/prompts/weight_predict.txt
Labels: AI, feature

#192 [AI/feat] 분석화면 백엔드 구축
  AI/data/food/food_data.csv
  AI/server/auth/decoded_token.py
  AI/server/db/crud.py
  AI/server/db/models.py
  AI/server/db/schema.py
  AI/server/main.py
  AI/server/routers/test.py
Labels: AI, feature

#193 Feat/#191
  BE/exceed/resources/gaebaljip-local-develop-environment/mariadb-init/01_schma.sql
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/BaseEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/HistoryEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/HistoryPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/HistoryRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomHistoryRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomHistoryRepositoryImpl.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomMemberRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomMemberRepositoryImpl.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/MemberConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetMaintainMealUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetTargetMealUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/HistoryPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/MemberPort.java
Labels: BE, feature

#204 [BE/fix] 시큐리티 관련 예외 핸들링
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/adapter/AuthController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/docs/SecurityExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/GlobalExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/domain/JwtManager.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/ExpiredJwtAuthenticationException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/ExpiredJwtException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/InvalidJwtAuthenticationException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/InvalidJwtException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/SecurityErrorCode.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/UnSupportedJwtException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/UnsupportedAuthenticationException.java
Labels: BE, fix

#205 [BE/feat] docker 관련 파일 수정
  BE/exceed/Dockerfile
  BE/exceed/docker-compose.yml
Labels: BE, feature
