Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-06, with the labels that each got.

#298 conflic 해결
  .github/ISSUE_TEMPLATE/issue_template.md
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  .gitignore
  README.md
  docs/브랜치 전략.md
Labels: AI, feature

#297 [BE/feat] 시간 측정 기능
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/Encryption.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/TimerAop.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/annotation/Timer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/handler/SendEmailEventListener.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/EmailAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/RedisAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/CheckCodeService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/EmailPort.java
Labels: BE

#302 docs: gitignore 수정
  .gitignore
Labels: AI, feature

#311 [AI/fix] 음식분류 결과를 음식명에서 음식의 PK로 변경
  AI/server/detect_model/food_classification/src/handler.py
  AI/server/detect_model/model/config/config.properties
Labels: AI, fix

#309 [BE/feat] 익명 사용자일 경우 예외 처리
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/Encryption.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/GlobalExceptionHandler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/log/LoggingFilter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/EmailAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/RedisAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/CheckCodeService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/domain/JwtManager.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/JwtAuthenticationPoint.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/SecurityErrorCode.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/exception/SignatureJwtException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/filter/JwtAuthenticationFilter.java
Labels: BE, feature

#313 [AI/fix] 사용자가 일주일 간 섭취한 영양성분 조회
  AI/server/db/crud.py
  AI/server/db/models.py
Labels: AI, fix

#315 [AI/fix] New Repository를 생성한 후의 에러 해결
  AI/requirements.txt
  AI/server/apis/api.py
  AI/server/db/crud.py
  AI/server/db/models.py
Labels: AI, fix

#317 AI 5차 스프린트 종료
  AI/requirements.txt
  AI/server/apis/api.py
  AI/server/db/crud.py
  AI/server/db/models.py
  AI/server/detect_model/food_classification/src/handler.py
  AI/server/detect_model/model/config/config.properties
Labels: AI

#319 fix/#318 : 내가 추가한 음식 조회 오류 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/port/out/FoodPort.java
Labels: bug, BE

#322 [BE/Feat] 테스트 컨테이너를 사용해 멱등성있는 테스트 환경 구축
  BE/exceed/build.gradle
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/ContainerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/ControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/DatabaseCleaner.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/IntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/SpecificMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/SpecificMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/OnBoardingControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/nutritionist/adapter/in/GetAchieveControllerTest.java
Labels: BE, feature

#327 [AI/docs] AI 브랜치의 PR 템플릿 동기화
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: AI, document

#326 [AI/fix] 음식분류모델 결과 반환 형태 변경
  AI/server/detect_model/food_classification/src/handler.py
Labels: AI, fix

#328 [AI/feat] 음식분류모델에 대한 Dockerfile 작성
  AI/server/detect_model/Dockerfile
  AI/server/detect_model/food_classification/src/create-mar.sh
  AI/server/detect_model/food_classification/src/requirements.txt
  AI/server/detect_model/model/config/config.properties
Labels: AI, feature
