Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-11, with the labels that each got.

#556 [BE/FIX] Swagger 403 응답 해결
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdatePasswordController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/security/config/SecurityConfig.java
Labels: bug, BE

#557 [BE/FIX] 식사 분석하는 수식 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/GStrategy.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/MealFoodEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/MeasureStrategy.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/MultipleStrategy.java
Labels: BE, fix

#562 [BE/FEAT] redis autocomplete 데이터 셋 변경
  BE/exceed/food_data.csv
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/data/RedisAutoComplete.java
Labels: BE

#565 [BE/FIX] 음식 자동완성 통합 테스트 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/MealFoodEntity.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/food/GetFoodIntegrationTest.java
Labels: BE, test

#568 [BE/FIX] 식사 목표 단,탄,지 구하는 계산식 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/member/Member.java
Labels: BE, fix

#574 [BE/FIX] 켈린더 상세 오늘 먹은 음식 조회 안 되는 오류 해결
  src/main/java/com/gaebaljip/exceed/adapter/in/meal/GetMealController.java
  src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  src/main/resources/db/testData_signup_after_2days_onboarding.sql
  src/test/java/com/gaebaljip/exceed/integration/meal/GetMealIntegrationTest.java
Labels: BE

#578 [BE/FEAT] 이메일 인증 방식 변경
  src/main/java/com/gaebaljip/exceed/adapter/in/member/CheckMemberEmailController.java
  src/main/java/com/gaebaljip/exceed/adapter/in/member/FindPasswordController.java
  src/main/java/com/gaebaljip/exceed/application/domain/member/Code.java
  src/main/java/com/gaebaljip/exceed/application/port/in/member/CheckSignUpMemberUsecase.java
  src/main/java/com/gaebaljip/exceed/application/service/member/CheckCodeService.java
  src/main/java/com/gaebaljip/exceed/application/service/member/CheckSignUpMemberService.java
  src/main/java/com/gaebaljip/exceed/application/service/member/CreateMemberService.java
  src/main/java/com/gaebaljip/exceed/common/Encryption.java
  src/main/java/com/gaebaljip/exceed/common/MailTemplate.java
  src/main/java/com/gaebaljip/exceed/common/event/handler/InCompleteSignUpMemberEventListener.java
  src/main/java/com/gaebaljip/exceed/common/event/handler/SendEmailEventListener.java
  src/main/java/com/gaebaljip/exceed/common/event/handler/SignUpMemberEventListener.java
  src/main/resources/templates/findPassword.html
  src/main/resources/templates/signup.html
Labels: BE, feature

#581 [BE/FIX] 온보딩을 한 날짜에 켈린더 상세 조회할 때 회원 조회가 안 되는 에러 해결
  src/main/java/com/gaebaljip/exceed/adapter/in/meal/GetMealController.java
  src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  src/main/java/com/gaebaljip/exceed/application/service/meal/ValidateBeforeSignupDateService.java
  src/main/java/com/gaebaljip/exceed/application/service/member/OnBoardingMemberService.java
  src/main/java/com/gaebaljip/exceed/application/service/nutritionist/ValidateSignUpBeforeMonthService.java
  src/main/resources/db/testData_signup_after_2days_onboarding.sql
  src/test/java/com/gaebaljip/exceed/application/domain/member/MemberEntityTest.java
  src/test/java/com/gaebaljip/exceed/integration/meal/GetMealIntegrationTest.java
Labels: bug, BE, fix

#583 [BE/FEAT] 인프라 재구성으로 인한 변경사항 반영
  docker-compose-prod.yml
  food_data.csv
  resources/gaebaljip-local-environment/setting.yml
  src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  src/main/java/com/gaebaljip/exceed/config/RedisConfig.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/test/java/com/gaebaljip/exceed/common/ContainerTest.java
  src/test/java/com/gaebaljip/exceed/integration/meal/GetMealIntegrationTest.java
Labels: BE, feature
