Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-03, with the labels that each got.

#148 [BE/refactor] 리팩토링 및 주석 추가
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/ApiResponseGenerator.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/TodayMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/Food.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetMealFoodResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/MealRecord.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/SpecificMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/out/FoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealFoodPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/S3Adapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/EatMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/UploadImageService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetSpecificMealQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/DailyMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/MealFoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/PresignedUrlPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/DailyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/adapter/in/GetAnalysisController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/application/GetAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/domain/DailyTarget.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/domain/MealNutrient.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/domain/Nutritionist.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/domain/JwtManager.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/filter/JwtAuthenticationFilter.java
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/SpecificMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/SpecificMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/nutritionist/GetAchieveIntegrationTest.java
Labels: BE, fix, refactor, document

#152 [BE/Setting] .env 파일 생성
  BE/exceed/.gitignore
Labels: BE, setting

#155 [BE/Docs] 주석 추가
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/EatMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/DailyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/Member.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/application/GetAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/domain/Nutritionist.java
Labels: BE, document

#164 [AI/Setting] 개발환경 세팅
  AI/server/.gitignore
  AI/server/__pycache__/main.cpython-39.pyc
  AI/server/apis/api.py
  AI/server/core/config.py
  AI/server/db/crud.py
  AI/server/db/database.py
  AI/server/db/models.py
  AI/server/detect_model/model.py
  AI/server/main.py
  AI/server/routers/diet_analysis.py
  AI/server/routers/food_detect.py
Labels: AI, setting
