Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-07, with the labels that each got.

#333 [BE/FEAT] : DTO Validation 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/ValidationMessage.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/CheckMemberRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/CreateFoodRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/GetAnalysisRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/MonthlyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/OnBoardingMemberRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/TodayMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/UpdateMemberRequest.java
Labels: BE, feature

#355 [AI/fix] dockerfile 오류 해결
  AI/food_classification/Dockerfile
  AI/food_classification/src/create-mar.sh
  AI/food_classification/src/handler.py
Labels: AI, fix

#357 [BE/test] 식사 정보 분석 관련 API 테스트 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/MealRecordDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/adapter/in/GetAnalysisController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/domain/Nutritionist.java
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/SpecificMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/nutritionist/GetAchieveIntegrationTest.java
Labels: BE, feature

#358 [BE/TEST] DTO Validation test
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/CreateFoodController.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/auth/AuthControllerIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/auth/adapter/in/AuthControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/CreateFoodIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/adapter/in/CreateFoodControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/OnBoardingControllerTest.java
Labels: BE

#362 [BE/test] 회원가입 API 테스트
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/AsyncConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CheckMemberEmailController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/OnBoardingController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/SignUpMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/VerifyEmailCheckedController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomMemberRepositoryImpl.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/ValidateEmailService.java
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/config/MockS3Config.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/config/MockSesConfig.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/SpecificMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/CheckMemberEmailIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/OnBoardingMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/SignUpMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestTestRequest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/OnBoardingControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/application/CreateMemberServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/application/OnBoardingMemberServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/application/ValidateEmailServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/nutritionist/GetAchieveIntegrationTest.java
Labels: BE, refactor, test

#366 [AI/fix] 모델 파라미터 파일 업로드
  .gitignore
  AI/food_classification/model/model_param.pt
Labels: AI, fix

#370 [AI/docs] 누락된 데이터 파일 추가
  AI/food_classification/labels/food_data.csv
Labels: AI, document

#372 [AI/fix] docker 사이즈 축소를 위한 코드 수정
  AI/food_classification/Dockerfile
  AI/food_classification/requirements.txt
Labels: AI, fix

#367 [Be/test] 식사 등록하는 API 테스트
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/S3Config.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/SesConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/port/out/FoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/EatMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/docs/EatMealExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/exception/InvalidGException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/exception/InvalidMultipleAndGException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/exception/MealError.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/InitializeS3Bucket.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/S3BucketInitializer.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/config/MockS3Config.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/config/MockSesConfig.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/application/EatMealServiceTest.java
  BE/exceed/src/test/resources/init-s3-bucket.sh
Labels: BE, refactor, test

#375 [BE/fix] docker compose restart 에러 해결
  BE/exceed/docker-compose.yml
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
Labels: BE, fix

#379 [BE/feat] 식사 분석하는 API 기능 변경에 따른 유스케이스 개발 및 기존 도메인 리팩토링
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/nutritionist/GetAnalysisController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/nutritionist/MonthlyTargetPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/AbstractAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/Analyzable.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/Analyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/CalorieAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/CalorieAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/CarbohydrateAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/CarbohydrateAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/FatAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/FatAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/Nutritionist.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/ProteinAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/ProteinAnalyzerFactory.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetAllAnalysisUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetAnalysisUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetCalorieAnalysisUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/member/MemberPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetAllCalorieAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetCalorieCalorieAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/AllAnalysisDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/AnalysisDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/CalorieAnalysisDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/GetAllAnalysisRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/GetCalorieAnalysisRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetAnalysisResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetCalorieAnalysisResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetMealFoodResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetMealResponse.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/nutritionist/GetAchieveControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/meal/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/nutritionist/GetAchieveIntegrationTest.java
Labels: BE, feature, refactor

#381 [BE/fix] 테스트 실패로인한 workflow 실패 해결
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/MealRecordDTO.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/meal/SpecificMealDTOControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/meal/GetMealIntegrationTest.java
Labels: BE, refactor

#382 [AI/feat] 데이터 변경
  AI/data/diet/preprocessed.csv
  AI/server/prompts/health_advice.txt
  AI/server/prompts/weight_carbo.txt
  AI/server/prompts/weight_fat.txt
  AI/server/prompts/weight_protein.txt
Labels: AI, feature

#393 [AI/feat] EC2 서버 구축(AI 서버)
  AI/server/Dockerfile
  AI/server/main.py
Labels: AI, feature

#394 [AI/fix] Dockerfile 수정 및 EC2 배포
  AI/server/Dockerfile
  AI/server/Hn19_22_preprocessed.csv
  AI/server/core/config.py
Labels: AI, feature, fix

#401 [BE/REFACTOR] 온보딩 여부 확인 API
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/OnBoardingController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/OnBoardingMemberQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/OnBoardingMemberUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/OnBoardingMemberService.java
Labels: BE, feature

#406 fix: EATceed/.gitignore 파일 수정
  .gitignore
Labels: AI, fix

#408 [AI/setting] .gitattributes 파일 위치 변경
  .gitattributes
  AI/food_classification/.gitattributes
Labels: AI, setting

#410 [AI/fix] AI 브랜치 스프린트 마감을 위한 충돌 해결
  .github/pull_request_template.md
Labels: AI, fix

#412 [AI/fix] AI 브랜치 스프린트 마감을 위한 충돌 해결
  .gitignore
Labels: AI, fix

#404 [BE/FIX] 빌드 에러 해결
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/auth/AuthController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/CreateFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/GetOwnFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/response/GetMealFoodResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/CheckMemberEmailController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/GetWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/OnBoardingController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/SignUpMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdateMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdateWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/nutritionist/GetAnalysisController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/auth/AuthUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/meal/EatMealCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/OnBoardingMemberCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/OnBoardingMemberQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/OnBoardingMemberUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetAllAnalysisUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/auth/AuthService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/food/CreateFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/food/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/food/GetOwnFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/CheckCodeService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/CreateMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/GetWeightService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/OnBoardingMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/UpdateWeightService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetAllCalorieAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetCalorieCalorieAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/EatMealFoodDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/EatMealRequest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/auth/AuthControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/food/CreateFoodControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/meal/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/member/OnBoardingControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/member/CreateMemberServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/port/in/meal/EatMealCommandTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/auth/AuthControllerIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/food/CreateFoodIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/meal/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/meal/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/OnBoardingMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/SignUpMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/nutritionist/GetAchieveIntegrationTest.java
Labels: BE, fix

#413 [BE/fix] 운영 서버에 반영
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/auth/AuthController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/CreateFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/GetOwnFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/response/GetMealFoodResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/CheckMemberEmailController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/GetWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/OnBoardingController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/SignUpMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdateMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdateWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/nutritionist/GetAnalysisController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/auth/AuthUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/meal/EatMealCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/OnBoardingMemberCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/OnBoardingMemberQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/OnBoardingMemberUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetAllAnalysisUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/auth/AuthService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/food/CreateFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/food/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/food/GetOwnFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/CheckCodeService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/CreateMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/GetWeightService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/OnBoardingMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/UpdateWeightService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetAllCalorieAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetCalorieCalorieAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/EatMealFoodDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/EatMealRequest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/auth/AuthControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/food/CreateFoodControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/meal/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/member/OnBoardingControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/member/CreateMemberServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/port/in/meal/EatMealCommandTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/auth/AuthControllerIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/food/CreateFoodIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/meal/EatMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/meal/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/OnBoardingMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/SignUpMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/nutritionist/GetAchieveIntegrationTest.java
Labels: BE

#376 [BE/TEST] 각종 테스트
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdateWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/request/UpdateMemberRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/log/LoggingFilter.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/member/UpdateMemberControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/member/UpdateWeightControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/infrastructure/adapter/in/EmitterControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/DeleteMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/GetWeightIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/UpdateMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/UpdateWeightIntegrationTest.java
Labels: BE, test

#416 [BE/test] 웹 계층 단위테스트 보충
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/auth/AuthControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/meal/GetMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/nutritionist/GetAchieveControllerTest.java
Labels: BE, refactor, test

#422 [BE/TEST] 음식 조회 테스트
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/food/FoodsPersistenceAdapter.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/food/GetFoodIntegrationTest.java
Labels: BE, test

#424 [BE/test] 하루에 먹은 식사 영양소를 계산하는 DailyMeal 도메인 리팩토링 및 테스트
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/ConsumedFood.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/DailyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/meal/Unit.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/meal/DailyMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/meal/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/meal/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetAllCalorieAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/AllAnalysisDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/CurrentMealDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/DailyMealDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/SpecificMealDTO.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/domain/meal/DailyMealTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/domain/nutritionist/CalorieAnalyzerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/service/nutritionist/GetAllCalorieAnalysisServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/factory/MealsFixtureFactory.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/factory/MemberFixtureFactory.java
Labels: BE, refactor, test

#426 [AI/fix] 응답 방식 변경
  AI/server/apis/api.py
  AI/server/auth/decoded_token.py
  AI/server/db/crud.py
  AI/server/db/models.py
  AI/server/main.py
  AI/server/routers/diet_analysis.py
Labels: AI, fix

#427 [Be/fix] 특정 날짜의 식사 정보 조회하는 API 오류 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/HistoryPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/custom/CustomHistoryRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/custom/CustomHistoryRepositoryImpl.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/custom/CustomMemberRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/custom/CustomMemberRepositoryImpl.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/member/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/meal/ValidateBeforeSignUpUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/member/HistoryPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/member/MemberPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/meal/ValidateBeforeSignupService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/GetTargetMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/meal/GetMealExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/meal/GetMealFoodExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/meal/InValidDateFoundException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/meal/MealError.java
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/meal/GetMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/out/jpa/member/custom/CustomHistoryRepositoryImplTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/out/jpa/member/custom/CustomMemberRepositoryImplTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/DatabaseTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/factory/MemberFixtureFactory.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/meal/GetMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/GetWeightIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/UpdateMemberIntegrationTest.java
Labels: bug, BE, fix, test

#430 [Be/Test] 테스트 환경 개선
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/auth/AuthControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/food/CreateFoodControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/meal/EatMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/meal/GetMealControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/member/OnBoardingControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/member/UpdateMemberControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/member/UpdateWeightControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/notify/EmitterControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/nutritionist/GetAchieveControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/ControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/IntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/food/GetFoodIntegrationTest.java
  BE/exceed/src/test/resources/logback-test.xml
Labels: BE, refactor, test

#433 [BE/FEAT] 이메일 인증 완료 기능(데브용)
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/EmailConfirmedController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/EmailConfirmedUseCase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/EmailConfirmedService.java
Labels: BE, feature

#437 fix/#436: EmailConfirmedController endPoint 설정
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/EmailConfirmedController.java
Labels: BE, fix

#441 [BE/FIX] 이메일 완료 기능 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/EmailConfirmedController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/EmailConfirmedService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/security/config/SecurityConfig.java
Labels: BE, fix
