Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-05, with the labels that each got.

#202 [AI/feat] 토큰 해석 예외처리
  AI/.gitattributes
  AI/.gitignore
  AI/server/auth/decoded_token.py
Labels: AI, feature

#208 [AI/setting] 중복된 config.properties 파일 삭제
  AI/server/detect_model/food_classification/config.properties
Labels: AI, setting

#209 Feat/#198
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/EatCeedStaticMessage.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/RedisUtils.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/RedisConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/GetAnalysisRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/MonthlyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/TodayMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/Analysis.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetFoodsResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/infrastructure/redis/RedisAutoComplete.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/infrastructure/redis/RedisUtils.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetSpecificMealQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/HistoryPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/RedisAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/WeightEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomHistoryRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomHistoryRepositoryImpl.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomMemberRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/custom/CustomMemberRepositoryImpl.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/MemberConverter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetMaintainMealUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetTargetMealUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/HistoryPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/MemberPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/adapter/in/GetAnalysisController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/application/GetAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/application/port/out/MonthlyTargetPort.java
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/IntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/SpecificMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/OnBoardingMemberIntegrationTest.java
  BE/food_data.csv
Labels: BE, feature

#210 Feat/#198
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/EatCeedStaticMessage.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/RedisUtils.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/RedisConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetFoodsResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/infrastructure/redis/RedisAutoComplete.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/infrastructure/redis/RedisUtils.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/RedisAdapter.java
  BE/food_data.csv
Labels: BE, feature

#212 fix/#211 : 통합 테스트 에러 해결
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/infrastructure/redis/RedisAutoComplete.java
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-prod.yml
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
  BE/food_data.csv
Labels: BE, fix

#213 [BE/feat] 모니터링 환경 세팅
  BE/exceed/Dockerfile
  BE/exceed/build.gradle
  BE/exceed/docker-compose.yml
  BE/exceed/food_data.csv
  BE/exceed/resources/gaebaljip-develop-environment/mariadb-conf/mariadb.conf
  BE/exceed/resources/gaebaljip-develop-environment/mariadb-init/00_init.sql
  BE/exceed/resources/gaebaljip-develop-environment/mariadb-init/01_schma.sql
  BE/exceed/resources/gaebaljip-develop-environment/prometheus/config/prometheus.yml
  BE/exceed/resources/gaebaljip-local-develop-environment/setting.yml
  BE/exceed/resources/gaebaljip-local-environment/.DS_Store
  BE/exceed/resources/gaebaljip-local-environment/mariadb-conf/mariadb.conf
  BE/exceed/resources/gaebaljip-local-environment/mariadb-init/00_init.sql
  BE/exceed/resources/gaebaljip-local-environment/mariadb-init/01_schma.sql
  BE/exceed/resources/gaebaljip-local-environment/prometheus/config/prometheus.yml
  BE/exceed/resources/gaebaljip-local-environment/setting.yml
  BE/exceed/scripts/reset.sh
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/ActuatorConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/security/config/SecurityConfig.java
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
Labels: bug, BE, feature, fix

#219 [AI/feat] Swagger 암호화 설정 구현
  .gitattributes
  .gitignore
  AI/server/core/config.py
  AI/server/main.py
  AI/server/requirements.txt
  AI/server/routers/test.py
Labels: AI, feature

#222 [BE/FEAT] : 음식 추가 기능
  BE/exceed/resources/gaebaljip-develop-environment/mariadb-init/01_schma.sql
  BE/exceed/resources/gaebaljip-local-environment/mariadb-init/01_schma.sql
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/CreateFoodRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/CreateFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/CreateFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/port/in/CreateFoodUseCase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/port/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/port/out/FoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/EatMealService.java
  BE/exceed/src/main/resources/db/testData.sql
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/CreateFoodIntegrationTest.java
Labels: BE, feature

#221 [AI/fix] 최종디렉토리에 위치해있던 .gitignore 파일 원위치
  .gitignore
Labels: AI, fix

#225 AI 3차 sprint 마감
  AI/.gitattributes
  AI/server/auth/decoded_token.py
  AI/server/core/config.py
  AI/server/detect_model/food_classification/config.properties
  AI/server/main.py
  AI/server/requirements.txt
  AI/server/routers/test.py
Labels: AI, feature

#224 [BE/FEAT] LogBack 도입
  BE/exceed/.gitignore
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/logback-spring.xml
Labels: BE, feature

#230 [BE/feat] 켈린더 반환값 형식 수정 및 회원가입 시 이메일 확인하는 기능
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/Analysis.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/SignUpMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/VerifyEmailCheckedService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/VerifyEmailCheckedUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/adapter/in/GetAnalysisController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/application/GetAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/nutritionist/domain/Nutritionist.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/SpecificMealIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/member/SignUpMemberIntegrationTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/nutritionist/GetAchieveIntegrationTest.java
  docs/브랜치 전략.md
Labels: BE, feature

#232 [BE/FIX] LoggingFilter 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/log/LoggingFilter.java
Labels: fix

#234 [AI/feat] 프롬프트 세분화
  AI/server/prompts/health_advice.txt
  AI/server/prompts/weight_carbo.txt
  AI/server/prompts/weight_fat.txt
  AI/server/prompts/weight_predict.txt
  AI/server/prompts/weight_protein.txt
Labels: AI, feature

#240 [AI/feat] 식습관 분석 API 구현
  AI/server/apis/api.py
  AI/server/main.py
  AI/server/prompts/health_advice.txt
  AI/server/routers/diet_analysis.py
Labels: AI, feature

#242 [AI/fix] 식습관 분석 API 오류 수정
  AI/server/routers/diet_analysis.py
Labels: AI, fix

#238 [BE/FEAT] food_data.csv 수정
  BE/exceed/food_data.csv
Labels: BE

#248 [BE/feat] Docker Volume과 log 파일 연동
  BE/exceed/docker-compose.yml
  BE/exceed/food_data.csv
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/data/MariaDBAutoComplete.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/data/RedisAutoComplete.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/redis/RedisUtils.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/port/out/FoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/health/HealthController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/RedisAdapter.java
  BE/exceed/src/main/resources/application-dev.yml
  BE/exceed/src/main/resources/application-local.yml
  BE/exceed/src/main/resources/application-prod.yml
  BE/exceed/src/main/resources/application-test.yml
  BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
Labels: BE, feature

#250 [BE/feat] 잘못된 오류 메시지 반환 수정
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/ValidateEmailService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/exception/AlreadySignUpMemberException.java
Labels: BE

#253 [AI/feat] 분석화면 기능에 필요한 CRUD 작업 수행
  AI/server/apis/api.py
  AI/server/db/crud.py
  AI/server/db/models.py
  AI/server/prompts/health_advice.txt
  AI/server/prompts/weight_carbo.txt
  AI/server/prompts/weight_fat.txt
  AI/server/prompts/weight_protein.txt
  AI/server/routers/diet_analysis.py
  AI/server/routers/food_detect.py
Labels: AI, feature

#256 [AI/FEAT] torchserve handler에 token decoding 기능 추가
  AI/server/detect_model/food_classification/src/handler.py
  AI/server/detect_model/model/config/config.properties
  AI/server/detect_model/model/model_store/foodcls.mar
Labels: AI, feature

#257 AI 3차 스프린트 마감
  AI/server/apis/api.py
  AI/server/db/crud.py
  AI/server/db/models.py
  AI/server/detect_model/food_classification/src/handler.py
  AI/server/detect_model/model/config/config.properties
  AI/server/detect_model/model/model_store/foodcls.mar
  AI/server/main.py
  AI/server/prompts/health_advice.txt
  AI/server/prompts/weight_carbo.txt
  AI/server/prompts/weight_fat.txt
  AI/server/prompts/weight_predict.txt
  AI/server/prompts/weight_protein.txt
  AI/server/routers/diet_analysis.py
  AI/server/routers/food_detect.py
Labels: AI

#252 [BE/FEAT] 회원탈퇴
  BE/exceed/resources/gaebaljip-develop-environment/mariadb-init/01_schma.sql
  BE/exceed/resources/gaebaljip-local-environment/mariadb-init/01_schma.sql
  BE/exceed/src/main/java/com/gaebaljip/exceed/auth/docs/AuthExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/DeleteMemberEvent.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/DomainEvent.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/EventPublisherAspect.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/Events.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/handler/DeleteMemberEventListener.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/port/out/FoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealFoodPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealFoodRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/MealFoodPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/out/MealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/DeleteMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/HistoryPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/HistoryRepository.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/DeleteMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/DeleteMemberUseCase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/HistoryPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/MemberPort.java
  BE/exceed/src/main/resources/db/testData.sql
Labels: BE, feature

#262 [BE/refactor] 회원가입 기능 개선
  BE/exceed/src/main/java/com/gaebaljip/exceed/ExceedApplication.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/Events.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/InfraEvent.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/SendEmailEvent.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/handler/SendEmailEventListener.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/AsyncConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/EmailAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/SendSignupEmailService.java
Labels: BE, refactor

#272 [AI/fix] 식습관 분석 프롬프트 출력값 형식 변경
  AI/server/prompts/health_advice.txt
  AI/server/prompts/weight_carbo.txt
  AI/server/prompts/weight_fat.txt
  AI/server/prompts/weight_protein.txt
Labels: AI, fix

#274 [AI/docs] README.md 수정
  README.md
Labels: AI, document

#278 [AI/fix] torchserve handler 내 token decoder 오류 수정
  AI/server/auth/decoded_token.py
  AI/server/detect_model/food_classification/src/handler.py
  AI/server/detect_model/model/model_store/foodcls.mar
Labels: AI, fix

#280 [AI/fix] torchserve에서 입력받는 이미지 형식을 URL에서 file 형태로 변경
  AI/server/detect_model/food_classification/src/handler.py
  AI/server/detect_model/model/model_store/foodcls.mar
Labels: AI, fix

#284 [BE/feat] 회원 몸무게 수정하는 기능
  BE/exceed/resources/gaebaljip-local-environment/mariadb-init/01_schma.sql
  BE/exceed/src/main/java/com/gaebaljip/exceed/ExceedApplication.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/UpdateWeightRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/UpdateWeightResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetFoodResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/in/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/port/in/GetFoodQuery.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/UpdateWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/EmailAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/UpdateMemberService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/UpdateWeightService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/UpdateMemberCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/UpdateWeightCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/UpdateWeightUsecase.java
Labels: BE, feature

#287 [BE/FEAT] 몸무게 조회 기능
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/request/UpdateMemberRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetWeightResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/GetWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberEntity.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetWeightService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetWeightUseCase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/Member.java
Labels: BE, feature

#283 [AI/feat] APScheduler 적용
  AI/server/apis/api.py
  AI/server/db/crud.py
  AI/server/db/schema.py
  AI/server/prompts/weight_carbo.txt
  AI/server/prompts/weight_fat.txt
  AI/server/prompts/weight_protein.txt
  AI/server/routers/diet_analysis.py
  AI/server/routers/test.py
Labels: AI, feature

#289 [AI/feat] 음식분류 모델이 음식을 감지하지 못한 상황에 대한 예외처리
  AI/server/detect_model/food_classification/src/handler.py
Labels: AI, feature
