Repository JNU-econovation/EATceed-BE, pull requests merged in 2024-10, with the labels that each got.

#510 [AI/fix] Torchserve 요청 관련 에러 재수정
  AI/food_classification/Dockerfile
  AI/food_classification/src/config.properties
Labels: AI, fix

#514 [AI/feat] 개발 / 운영 환경 나누기
  AI/.gitignore
  AI/server/core/config.py
Labels: AI, feature

#516 [BE/FIX] 캐시 정합성 문제 해결
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdateWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/nutritionist/response/GetMonthlyAnalysisResponse.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/member/HistoryPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/nutritionist/MonthlyMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/scheduler/quartz/DailyAnalysisCacheUpdater.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/scheduler/quartz/UpdateCacheScheduler.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/MealFoodsAnalyzer.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/MonthlyMeal.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/domain/nutritionist/VisitChecker.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetDailyAnalysisCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetDailyAnalysisUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetDaysAnalysisCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetDaysAnalysisUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetMonthlyAnalysisCommand.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/nutritionist/GetMonthlyAnalysisUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/meal/DailyMealPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/member/HistoryPort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/meal/GetCurrentMealService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/UpdateWeightService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetDailyAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetDaysAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/nutritionist/GetMonthlyAnalysisService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/RedisKeys.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/RedisScanPattern.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/DaysMealDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/DaysMealRecordDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/GetDaysAnalysisDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/MonthlyMealRecordDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/NowMonthAnalysisCache.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/config/CacheConfig.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/member/UpdateWeightControllerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapterTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/out/scheduler/quartz/DailyAnalysisCacheUpdaterTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/domain/nutritionist/MealFoodsAnalyzerTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/service/nutritionist/GetAnalysisServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/application/service/nutritionist/GetDailyAnalysisServiceTest.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/common/factory/MonthlyMealFixtureFactory.java
Labels: BE, feature, fix

#518 [AI/feat] 음식 이미지 분석 API 구현
  AI/.gitignore
  AI/server/apis/api.py
  AI/server/core/config.py
  AI/server/db/models.py
  AI/server/docker-compose-dev.yaml
  AI/server/main.py
  AI/server/prompts/food_image_analyze.txt
  AI/server/routers/diet_analysis.py
  AI/server/routers/food_image_analysis.py
  AI/server/schema.sql
Labels: AI, feature

#525 [BE/FEAT] 엑세스 토큰 재발급(리프레시 토큰)
  BE/exceed/build.gradle
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/auth/AuthController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/jpa/meal/MealPersistenceAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/out/redis/RedisAdapter.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/auth/AuthUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/out/member/CodePort.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/auth/AuthService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/EatCeedStaticMessage.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/auth/LoginExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/auth/ReissueTokenExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/HttpRequestDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/LoginResponseDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/dto/TokenDTO.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/auth/AuthError.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/auth/NotFoundRefreshTokenException.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/security/config/SecurityConfig.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/security/domain/JwtManager.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/security/domain/JwtResolver.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/security/exception/SecurityErrorCode.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/auth/AuthControllerTest.java
Labels: BE, feature, refactor

#529 [BE/TEST] 로그인 테스트 수정
  BE/exceed/src/test/java/com/gaebaljip/exceed/adapter/in/auth/AuthControllerTest.java
Labels: bug, BE, test

#523 [BE/FEAT] 비밀번호 변경 API 구현
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/FindPasswordController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/request/FindPasswordRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/MailTemplate.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/member/FindPassword_updatePasswordExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/member/FindPassword_validateEmailExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/event/handler/SendEmailEventListener.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/security/config/SecurityConfig.java
  BE/exceed/src/main/resources/templates/findPassword.html
Labels: BE, feature, fix

#545 [AI/feat] AI용 레포지토리로 이동으로 인한 Merge 진행
  AI/data/diet/.gitignore
  AI/data/diet/Hn19_22_preprocessed.csv
  AI/data/diet/knhanes_Data_Preprocessing.ipynb
  AI/data/diet/preprocessed.csv
  AI/data/food/.gitignore
  AI/data/food/food_data.csv
  AI/data/food/food_data_preprocessing.ipynb
  AI/data/food/food_data_preprocessing.py
  AI/docker-compose.yml
  AI/food_classification/.gitattributes
  AI/food_classification/Dockerfile
  AI/food_classification/labels/403food.names
  AI/food_classification/labels/food_data.csv
  AI/food_classification/labels/food_labels.csv
  AI/food_classification/model/model_param.pt
  AI/food_classification/model/yolov3-spp-403cls.cfg
  AI/food_classification/requirements.txt
  AI/food_classification/src/auth/decoded_token.py
  AI/food_classification/src/config.properties
  AI/food_classification/src/core/config.py
  AI/food_classification/src/create-mar.sh
  AI/food_classification/src/handler.py
  AI/food_classification/src/utils/darknet.py
  AI/food_classification/src/utils/torch_utils.py
  AI/server/.dockerignore
  AI/server/apis/api.py
  AI/server/data/analysis_diet.csv
  AI/server/docker-compose-dev.yaml
  AI/server/init/schema.sql
  AI/server/test/image/부대찌개_1622_768.txt
  AI/server/test/image/분식_768_768.txt
  AI/server/test/image/식판_768_1364.txt
  AI/server/test/image/파스타_768_1364.txt
  AI/server/test/test_food_image_analysis.py
Labels: AI, feature

#547 [BE/Docs] Swagger 문서 개선
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/auth/AuthController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/CreateFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/DeleteFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/GetFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/food/GetOwnFoodController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/EatMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/meal/GetMealController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/CheckMemberEmailController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/DeleteMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/FindPasswordController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/OnBoardingController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/SignUpMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdateMemberController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdateWeightController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/VerifyEmailCheckedController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/nutritionist/GetAnalysisController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/SwaggerTag.java
Labels: BE, document

#549 [BE/Feat] 비밀번호 변경하는 API 개발
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/UpdatePasswordController.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/adapter/in/member/request/UpdatePasswordRequest.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/port/in/member/UpdatePasswordUsecase.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/application/service/member/UpdatePasswordService.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/docs/member/UpdatePasswordExceptionDocs.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/member/MemberError.java
  BE/exceed/src/main/java/com/gaebaljip/exceed/common/exception/member/SamePasswordException.java
  BE/exceed/src/test/java/com/gaebaljip/exceed/integration/member/UpdatePasswordIntegrationTest.java
Labels: BE, feature
