Repository JNU-econovation/EATceed-BE, pull requests merged in 2025-01, with the labels that each got.

#610 [BE/FEAT] 스웨거 비밀번호 설정
  src/main/java/com/gaebaljip/exceed/common/EatCeedStaticMessage.java
  src/main/java/com/gaebaljip/exceed/common/helper/SpringEnvironmentHelper.java
  src/main/java/com/gaebaljip/exceed/common/security/config/SecurityConfig.java
  src/main/java/com/gaebaljip/exceed/common/security/exception/JwtAuthenticationPoint.java
  src/main/java/com/gaebaljip/exceed/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/gaebaljip/exceed/common/swagger/SwaggerCannotProdException.java
  src/main/java/com/gaebaljip/exceed/common/swagger/SwaggerError.java
Labels: BE, feature

#615 [BE/FEAT] 회원탈퇴시 이메일 발송
  src/main/java/com/gaebaljip/exceed/common/MailTemplate.java
  src/main/java/com/gaebaljip/exceed/common/event/handler/DeleteMemberEventListener.java
  src/main/resources/application-dev.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application-test.yml
  src/main/resources/templates/withdraw.html
Labels: BE, feature

#617 [BE/FEAT] URL PREFIX로 운영 환경 및 개발 환경 분리하기
  docker-compose-dev.yml
  docker-compose-monitoring.yml
  docker-compose-prod.yml
  docker-compose.yml
  resources/gaebaljip-develop-environment/mariadb-conf/mariadb.conf
  resources/gaebaljip-develop-environment/mariadb-init/01_schema.sql
  resources/gaebaljip-local-environment/mariadb-init/02_data.sql
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: BE, feature

#619 [BE/FEAT] 민감 정보 동의 여부 받기
  resources/gaebaljip-develop-environment/mariadb-init/01_schema.sql
  resources/gaebaljip-local-environment/mariadb-init/01_schema.sql
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/GetAgreementController.java
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/UpdateAgreementController.java
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/request/AgreeSensitiveDataRequest.java
  src/main/java/com/gaebaljip/exceed/adapter/in/agreement/response/GetSensitiveDataAgreeResponse.java
  src/main/java/com/gaebaljip/exceed/adapter/in/member/request/SignUpMemberRequest.java
  src/main/java/com/gaebaljip/exceed/application/domain/agreement/AgreementEntity.java
  src/main/java/com/gaebaljip/exceed/application/port/in/agreement/AgreeSensitiveDataUsecase.java
  src/main/java/com/gaebaljip/exceed/application/service/agreement/AgreeSensitiveDataService.java
  src/main/java/com/gaebaljip/exceed/application/service/member/CreateMemberService.java
  src/main/java/com/gaebaljip/exceed/common/docs/agreement/AgreeSensitiveDataDocs.java
  src/main/java/com/gaebaljip/exceed/common/dto/GetAgreementDTO.java
  src/main/java/com/gaebaljip/exceed/common/exception/agreement/AgreementError.java
  src/main/java/com/gaebaljip/exceed/common/exception/agreement/InvalidSensitiveDataAgreeException.java
  src/main/resources/db/testData.sql
  src/main/resources/db/testData_signup_after_2days_onboarding.sql
  src/test/java/com/gaebaljip/exceed/application/member/CreateMemberServiceTest.java
  src/test/java/com/gaebaljip/exceed/integration/member/OnBoardingMemberIntegrationTest.java
  src/test/java/com/gaebaljip/exceed/integration/member/SignUpMemberIntegrationTest.java
  src/test/java/com/gaebaljip/exceed/integration/member/VerifyEmailCheckedIntegrationTest.java
Labels: BE, feature

#621 fix/#620: 마스킹 해제, 로그 파일 90일동안 보존 되도록 수정
  src/main/java/com/gaebaljip/exceed/adapter/in/notify/EmitterController.java
  src/main/java/com/gaebaljip/exceed/adapter/out/scheduler/quartz/UpdateWeightEventListener.java
  src/main/java/com/gaebaljip/exceed/adapter/out/scheduler/quartz/job/UpdateWeightEmitterJob.java
  src/main/java/com/gaebaljip/exceed/application/service/member/UpdateWeightService.java
  src/main/resources/logback-spring.xml
  src/test/java/com/gaebaljip/exceed/adapter/in/notify/EmitterControllerTest.java
  src/test/java/com/gaebaljip/exceed/common/ControllerTest.java
Labels: BE, fix

#626 [BE/FIX] 딥링크를 전달하는 API에서 Nginx 404 NOT FOUND 오류 해결
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
Labels: bug, BE

#630 [BE/HOTFIX] AOS 요청 사항 반영 (예외 메시지 수정)
  src/main/java/com/gaebaljip/exceed/common/ValidationMessage.java
Labels: BE, hotfix

#632 [BE/FIX] CSV 파일 변경
  food_data.csv
  src/test/java/com/gaebaljip/exceed/integration/food/GetFoodIntegrationTest.java
Labels: BE, fix

#633 [Release] Version 1.1.0 배포
  food_data.csv
  src/test/java/com/gaebaljip/exceed/integration/food/GetFoodIntegrationTest.java
Labels: BE

#635 [BE/FIX] schema.sql 수정
  resources/gaebaljip-develop-environment/mariadb-init/01_schema.sql
Labels: BE
